#ifndef __SETTINGS_H
#define __SETTINGS_H

#define HISTORY_FILE "._PAST_EVENTS_.txt"
#define HISTORY_SIZE 15

#define MAX_NAME_LENGTH 1024
#define MAX_PATH_LENGTH 1024
#define MAX_COMMAND_LEN 4096
#define MAX_ARGS 100

#endif